{% set data = load_setup_py_data() %}

package:
  name: pyjac
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=2.7,<3|>=3.5,{{PY_VER}}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - pyyaml >=3.11
    - numpy >=1.9.0
    - bitarray >=0.8.1
    - cython >=0.23.1
    - optionloop >1.0.3
    - cantera >=2.3.0

test:
  imports:
    - pyjac

  requires:
    - pytest >=3.0.1

  commands:
    - pytest -vv --pyargs pyjac

about:
  home: data['url']
  license: MIT License
  license_file: LICENSE
  license_family: MIT

  summary: data['description']
  description: data['long_description']
  doc_url: https://slackha.github.io/pyJac/
  dev_url: data['url']
